### ISSUE TITLE
Type error: Can only assign to unbound variables, _parent_org_271 is not unbound

### ISSUE THREAD

**Issue by kc-fiddler** [osohq/oso-github-sqlalchemy#2]
after updating to
```
# pip list | grep oso
flask-oso        0.8.0
oso              0.11.0
sqlalchemy-oso   0.5.0
```

 the `oso-github-sqlalchemy` example complains about 
```
# flask run
 * Serving Flask app "app:create_app(None, True)"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2021-02-18 01:31:18,790] ERROR in app: Exception on /orgs/2/repos [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/oso-github-sqlalchemy/app/routes.py", line 31, in repos_index
    return {f"repos": [repo.repr() for repo in repos]}
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3531, in __iter__
    context = self._compile_context()
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 4069, in _compile_context
    new_query = fn(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/events.py", line 2719, in wrap
    return fn(*arg, **kw)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_oso/session.py", line 51, in _before_compile
    return _authorize_query(query)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_oso/session.py", line 81, in _authorize_query
    authorized_filter = authorize_model(oso, user, action, query.session, entity)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy_oso/auth.py", line 82, in authorize_model
    for result in results:
  File "/usr/local/lib/python3.7/site-packages/polar/polar.py", line 141, in query
    for res in Query(query, host=host, bindings=bindings).run():
  File "/usr/local/lib/python3.7/site-packages/polar/query.py", line 45, in run
    ffi_event = self.ffi_query.next_event()
  File "/usr/local/lib/python3.7/site-packages/polar/ffi.py", line 92, in next_event
    event = check_result(event)
  File "/usr/local/lib/python3.7/site-packages/polar/ffi.py", line 152, in check_result
    raise Error().get()
polar.exceptions.PolarTypeError: trace (most recent evaluation last):
      allow(<app.models.User object at 0x7f8862b4ed50>, "READ", resource)
  in rule allow at line 8, column 9
    resource_role_applies_to(resource, role_resource) and
        user_in_role(user, role, role_resource) and
        role_allow(role, action, resource)
  in rule allow at line 8, column 9
    resource_role_applies_to(resource, role_resource)
  in rule resource_role_applies_to at line 26, column 5 in file app/authorization.polar
    parent_org := repo.organization and
    parent_org matches Organization
  in rule resource_role_applies_to at line 26, column 5 in file app/authorization.polar
    parent_org := repo.organization
  in rule resource_role_applies_to at line 26, column 5 in file app/authorization.polar
    parent_org := repo.organization
Type error: Can only assign to unbound variables, _parent_org_271 is not unbound. at line 26, column 5 in file app/authorization.polar
127.0.0.1 - - [18/Feb/2021 01:31:18] "GET /orgs/2/repos HTTP/1.1" 500 -
^CException during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140223748040448 and this is thread id 140223810361152.
Exception closing connection <sqlite3.Connection object at 0x7f8862bfcd50>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140223748040448 and this is thread id 140223810361152.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 564, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140223748040448 and this is thread id 140223810361152.
Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140223748040448 and this is thread id 140223810361152.
Exception closing connection <sqlite3.Connection object at 0x7f8862bfcab0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 558, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140223748040448 and this is thread id 140223810361152.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 564, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140223748040448 and this is thread id 140223810361152.
```

This seems to be stemming from
```
### An organization's roles apply to its child repositories
resource_role_applies_to(repo: Repository, parent_org) if
    parent_org := repo.organization and
    parent_org matches Organization;
```

where the assignment operator `:=` is being used in line 26. If that's changed to just `=`, things seem to work fine.

**Comment by samscott89** [comment]
Thank you for reporting this. This does look indeed look like a bug. The problem is using the assignment operator with a rule parameter.

We previously allowed this, since we didn't differentiate between a variable that was not previously and one that was unbound (had no assigned value).

This was a little inconsistent:

e.g.
```
query> x = y and x := 1
PolarTypeError
trace (most recent evaluation last):
  in query at line 1, column 1
    x = y and x := 1
  in query at line 1, column 11
    x := 1
Type error: Can only assign to unbound variables, x is bound to value y. at line 1, column 11
```
vs

```
query> x = y and y := 1
y = 1
x = 1
```

We'll work on a fix. But in the meantime, yes you can use `=` instead without issue.
